version: '3'

services:
    app-php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-apache-php
        restart: always
        volumes:
            - ./app:/var/www/html
        ports:
            - "8080:80"
        networks:
            - app-network
    app-mysql:
        image: mysql:5.7
        container_name: app-mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/database/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
